//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingleFolderAutomatedMover.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SingleFolderAutomatedMover.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all the fields.
        /// </summary>
        internal static string FormConfiguration_buttonSave_Click_Please_fill_in_all_the_fields {
            get {
                return ResourceManager.GetString("FormConfiguration_buttonSave_Click_Please_fill_in_all_the_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Configuration.
        /// </summary>
        internal static string FormConfiguration_FormConfiguration_Load_Set_Configuration {
            get {
                return ResourceManager.GetString("FormConfiguration_FormConfiguration_Load_Set_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service has started.
        ///.
        /// </summary>
        internal static string FormMain_button_ServiceHasStarted {
            get {
                return ResourceManager.GetString("FormMain_button_ServiceHasStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service has stopped.
        ///.
        /// </summary>
        internal static string FormMain_buttonStop_Click_ {
            get {
                return ResourceManager.GetString("FormMain_buttonStop_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automated Mover.
        /// </summary>
        internal static string FormMain_FormMain_Load_Automated_Mover {
            get {
                return ResourceManager.GetString("FormMain_FormMain_Load_Automated_Mover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration not found, opening the settings windows..
        /// </summary>
        internal static string FormMain_FormMain_Load_Configuration_not_found__opening_the_settings_windows_ {
            get {
                return ResourceManager.GetString("FormMain_FormMain_Load_Configuration_not_found__opening_the_settings_windows_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No settings saved, stopping program..
        /// </summary>
        internal static string FormMain_FormMain_Load_No_settings_saved__stopping_program_ {
            get {
                return ResourceManager.GetString("FormMain_FormMain_Load_No_settings_saved__stopping_program_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple AutoMover.
        /// </summary>
        internal static string FormMain_FormMain_Load_Simple_AutoMover {
            get {
                return ResourceManager.GetString("FormMain_FormMain_Load_Simple_AutoMover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  was .
        /// </summary>
        internal static string FormMain_fsw_Changed__was_ {
            get {
                return ResourceManager.GetString("FormMain_fsw_Changed__was_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///LastError = .
        /// </summary>
        internal static string FormMain_MoveFile_ {
            get {
                return ResourceManager.GetString("FormMain_MoveFile_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect.
        /// </summary>
        internal static string FormMain_MoveFile_Failed_to_connect {
            get {
                return ResourceManager.GetString("FormMain_MoveFile_Failed_to_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to .
        /// </summary>
        internal static string FormMain_MoveFile_Failed_to_connect_to_ {
            get {
                return ResourceManager.GetString("FormMain_MoveFile_Failed_to_connect_to_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///.
        /// </summary>
        internal static string NewLine {
            get {
                return ResourceManager.GetString("NewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
    }
}
